# 동일한 회원이 동일한 상품을 재구매한 데이터
SELECT DISTINCT A.USER_ID, A.PRODUCT_ID
FROM ONLINE_SALE as A, ONLINE_SALE AS B
WHERE A.USER_ID = B.USER_ID
and A.PRODUCT_ID = B.PRODUCT_ID
and A.SALES_DATE != B.SALES_DATE
ORDER BY A.USER_ID, A.PRODUCT_ID desc